DROP TABLE IF EXISTS mp_votes CASCADE;

CREATE TABLE mp_votes (
  id SERIAL PRIMARY KEY NOT NULL, 
  mp_id INTEGER NOT NULL,
  motion_id INTEGER NOT NULL REFERENCES motions(id) ON DELETE CASCADE,
  voted_yea BOOLEAN NOT NULL,
  voted_nay BOOLEAN NOT NULL,
  vote_paired BOOLEAN NOT NULL
);