-- 7 3 5 4 2 1 6

DROP TABLE IF EXISTS mp_votes CASCADE;

CREATE TABLE mp_votes (
  id SERIAL PRIMARY KEY NOT NULL, 
  mp_id INTEGER NOT NULL REFERENCES mps(id) ON DELETE CASCADE,
  motion_id INTEGER NOT NULL REFERENCES motions(id) ON DELETE CASCADE,
  voted_yea BOOLEAN NOT NULL
);