DROP TABLE IF EXISTS motions CASCADE;

CREATE TABLE motions (
  id SERIAL PRIMARY KEY NOT NULL, 
  vote_num INTEGER NOT NULL,
  parl_num INTEGER NOT NULL,
  sess_num INTEGER NOT NULL,
  sitting_num INTEGER,
  bill_num VARCHAR(255),
  date TIMESTAMP NOT NULL,
  result VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL
);