DROP TABLE IF EXISTS user_votes CASCADE;

CREATE TABLE user_votes (
  id SERIAL PRIMARY KEY NOT NULL, 
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  motion_id INTEGER REFERENCES motions(id) ON DELETE CASCADE,
  voted_yea BOOLEAN NOT NULL
);